version: '3.6'

services:
  openvpn-server:
    build: 
      dockerfile: Dockerfile
      target: openvpn
      context: .
    network_mode: host
    command: [ "--cd", "/opt/openvpn", "--config", "/opt/openvpn/openvpn_udp.conf" ]
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./conf
        target: /opt/openvpn/conf
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
  openvpn-tcp-server:
    build: 
      dockerfile: Dockerfile
      target: openvpn
      context: .
    network_mode: host
    command: [ "--cd", "/opt/openvpn", "--config", "/opt/openvpn/openvpn_tcp.conf" ]
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./conf
        target: /opt/openvpn/conf
      - type: bind
        source: /dev/net/tun
        target: /dev/net/tun
  openssl:
    build: 
      dockerfile: Dockerfile
      target: install_tools
      context: .
    network_mode: host
    entrypoint: /bin/bash
    command: [ 
        "-c", 
        "echo keeping container up ...; while true; sleep 1; do /bin/sleep 10; done"
    ]
    volumes:
      - type: bind
        source: ./conf
        target: /opt/openvpn/conf
