[req]
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
countryName                     = FR
stateOrProvinceName             = Alsace ## Print this message
localityName                    = Strasbourg ## Print this message
0.organizationName              = 37rtm ## Print this message
organizationalUnitName          = Admin ## Print this message
commonName                      = p52 ## Print this message
emailAddress                    = heim.nico@gmail.com ## Print this message

[alt_names]
DNS.1 = vpn.37rtm.fr