[project]

name = "openvpn-scripts"
requires-python = ">=3.11"
version = "0.1.0"

dependencies = ["jinja2", "pyyaml"]

[project.optional-dependencies]

dev = [
    "pylint", 
    "pytest",
    "jinja-templating @ file:///app/JinjaTemplating", 
]


[tool.pytest.ini_options]

log_cli = "True"
log_cli_level = "DEBUG"
